### ISSUE TITLE
Reference @gadenbuie's presentation materials

### ISSUE THREAD

**Issue by wlandau** [ropenscilabs/drake-manual#102]
- https://github.com/gadenbuie/drake-intro/
- https://pkg.garrickadenbuie.com/drake-intro/#1

**Comment by wlandau** [comment]
@gadenbuie, where and when did you first give the workshop?

**Comment by gadenbuie** [comment]
I presented it Friday, 19 July 2019 at Bio-Data Club held at Moffitt Cancer Center in Tampa, FL. Thanks for sharing!

**Comment by wlandau** [comment]
Thank *you* for the materials and for teaching `drake`. It is such a boon when someone else with a different point of view releases such high-quality work!
