### ISSUE TITLE
Add Tiernan Martin's talk

### ISSUE THREAD

**Issue by wlandau** [ropenscilabs/drake-manual#114]
@tiernanmartin, may I link to your satRdays presentation [here](https://ropenscilabs.github.io/drake-manual/index.html#presentations)?

I recall you gave a lightning talk on implementing `drake` workflows as packages, but I cannot seem to find it.

**Comment by tiernanmartin** [comment]
Sure!

FYI — it was actually a [Cascadia R Conference 2019](https://cascadiarconf.org/) lightning talk. Unfortunately, there aren't any videos of the presentation — there was a technical problem with the recording equipment, I believe —
but you are welcome to share the presentation PDF that I used during the talk:

  - [drakepkg-slides-cascadiarconf2019.pdf](https://github.com/tiernanmartin/drakepkg/raw/master/drakepkg-slides-cascadiarconf2019.pdf)

**Comment by wlandau** [comment]
Thanks!
