### ISSUE TITLE
Reference Matt Dray's presentation

### ISSUE THREAD

**Issue by wlandau** [ropenscilabs/drake-manual#115]
@matt-dray, I love [your slides from Coffee & Coding](https://github.com/matt-dray/drake-egg-rap/blob/master/docs/drake-presentation.pdf). May I reference them [here in the manual](https://ropenscilabs.github.io/drake-manual/index.html#presentations)?

**Comment by matt-dray** [comment]
Yes, absolutely!

**Comment by wlandau** [comment]
Added. Please feel free to correct me on the details.
