### ISSUE TITLE
More explicit integration with the workflow management paradigm by Jenny Bryan et al.

### ISSUE THREAD

**Issue by wlandau** [ropenscilabs/drake-manual#41]
The ["What they forgot to teach about R"](https://www.rstudio.com/workshops/what-they-forgot-to-teach-you-about-r/) paradigm is friendly, popular, and impactful, and much of its success comes from its limited scope. From [a recent PLOS Computational Biology article](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510) by @jennybc et al.:

> We have deliberately left many good tools and practices off our list, including some that we use daily, because they only make sense on top of the core practices described above or because it takes a larger investment before they start to pay off.

and

> Tools like Make were originally developed to recompile pieces of software that had fallen out of date... However, newcomers can achieve the same behavior by writing shell scripts that rerun everything; these may do unnecessary work, but given the speed of today's machines, that is unimportant for small projects.

Even so, `drake` adds value to this space.

- It is fully compatible with the authors' recommendations ([example: numbered scripts](https://twitter.com/wmlandau/status/1040923167903100928)).
- It is friendly to new users ([example discussion](https://twitter.com/WeAreRLadies/status/1047577305432899589)) especially in the space of Make-like tools.
- Even for small projects, it helps by encouraging tidiness and readability (mentions [here](https://twitter.com/ashiklom711/status/1002764095467212800) and [here](https://twitter.com/WeAreRLadies/status/1048458272800485376)).

I plan to write a special chapter to go through the best practices in [the article](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510) and spell out all the parallels point-by-point.

**Comment by jennybc** [comment]
Note https://github.com/jennybc/whattheyforgot/issues/30 😀

Feedback that will reveal my ignorance of drake but still maybe helpful. I think a really important thing when "selling" Git/GitHub and RStudio Projects is that you can implement at project start _or later_. These folders are still "just" regular folders on your hard drive, just with some extra stuff in hidden places. You could also delete `.git/` or `foo.Rproj` at any moment and be back where you started.

I think it would be great if the effort you outline above addresses this angle specifically for drake. I think people like to know whether $NEW_THING works with their old stuff and if it locks them into something "proprietary" (not in the commercial sense here, but in the workflow sense). I think people will want to know: Can I use drake with my existing scripts? If I have a drake workflow, does my existing script development / application workflow have to change? That sort of stuff.

**Comment by wlandau** [comment]
Migration of old projects to `drake` does require some work, and it is worth walking through the process. I am glad you brought it up, I have not thought about it enough.

Migration is easiest when most of the code already consists of nice small functions ([fortunately already a best practice](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510#sec005)). But it still requires writing a [workflow plan data frame](https://ropenscilabs.github.io/drake-manual/plans.html), which is like a `Makefile` in tidy data format. I have tried to make it easier to convert scripts and R Markdown reports into plans ([code_to_plan()](https://ropensci.github.io/drake/reference/code_to_plan.html), [example](https://github.com/wlandau/drake-examples/tree/master/code_to_plan)). There are other smaller adjustments too, such as the reliance on `drake`'s cache.

**Comment by wlandau** [comment]
More thoughts on https://github.com/ropenscilabs/drake-manual/issues/41#issuecomment-427721095.

>  I think a really important thing when "selling" Git/GitHub and RStudio Projects is that you can implement at project start *or later*.

This is the exact reason I was initially so resistent to using `Makefile`s for research in grad school. My dissertation project was half-implemented at the time, and I thought an overarching `Makefile` would require too much refactoring.

But for preexisting `purrr`-centric projects, the transition should be smoother now because of `drake`'s new [`map_plan()`](https://ropenscilabs.github.io/drake-manual/plans.html#map_plan) function. I might start with a half-completed or mostly completed project where each `pmap()` iteration is nontrivially expensive.

**Comment by wlandau** [comment]
Also

> You could also delete .git/ or foo.Rproj at any moment and be back where you started.

I will write a couple API functions to make it easier to give up `drake` (ref: https://github.com/ropensci/drake/issues/547). I think `code_to_plan()`, `plan_to_code()` and `plan_to_rmd()` will be part of this chapter.

**Comment by wlandau** [comment]
Sketch of an outline for a new chapter:

1. Start with a workflow with [numbered scripts](https://speakerdeck.com/jennybc/how-to-name-files), e.g. `01_data.R`, `02_munge.R`, `03_analysis.R`, etc.
2. Make a function out of each script (https://github.com/ropensci/drake/issues/994).
3. Call all the functions in a simple plan.
4. Iterate between `drake_plan()` and `vis_drake_graph()` to connect the targets in the correct order. End up with a working plan.
5. Walk through some refactoring.
    1. Edit each script file: put all the code in a function.  
    2. Replace `script_to_function()` with `source()`.
    3. Decompose the functions into smaller functions with formal arguments.

cc @thebioengineer

**Comment by thebioengineer** [comment]
@wlandau Are you thinking a complete new chapter, or editing and expanding upon chapter 5 in the "## Script file pitfalls" section? I am happy to do either, but I wanted to make sure we are on the same page. 

Based on what we have talked about, a chapter on "Pre-existing Script-based workflows" (working title 😄) is what we need since there are multiple parts to the process.

**Comment by wlandau** [comment]
Now that you bring it up, I think some stuff *could* go right after https://ropenscilabs.github.io/drake-manual/projects.html#script-file-pitfalls. It's a great place for https://github.com/ropenscilabs/drake-manual/issues/41#issuecomment-524367653 and `code_to_function()`.

But maybe we want to start at step 0 instead of step 1: what are functions, why do we care about them, and how do we leverage them in workflows? (I plan to spend much of [tomorrow's rOpenSci Community Call](https://ropensci.org/blog/2019/08/08/commcall-sep2019/) on this.) Seems like such a discussion is important and lengthy enough to deserve its own chapter.

**Comment by thebioengineer** [comment]
I agree - perhaps noting the pitfall and then linking to the new chapter?

**Comment by wlandau** [comment]
Sure, sounds like a good plan.

**Comment by wlandau** [comment]
[`Rclean`](https://github.com/provtools/rclean) may also have a role in this chapter. It uses code analysis to tease out individual results from large R scripts, and it may help users write smaller, cleaner functions to replace scripts. Currently [under review by rOpenSci](https://github.com/ropensci/software-review/issues/327).

**Comment by wlandau** [comment]
cc @MKLau

**Comment by wlandau** [comment]
Thanks to @thebioengineer, we now have `code_to_function()` in development `drake`! Ellis, I think you earned the right of first refusal to take the lead on writing this chapter. Interested?

**Comment by thebioengineer** [comment]
If you dont mind, I am happy to take the first crack at it and collaborate. I think I have an idea of how you want to approach this and am definitely open to critiques. I've been waiting until we finalized 'code_to_funtion()' to start on this. :)

**Comment by wlandau** [comment]
Awesome, thank you Ellis!

**Comment by MKLau** [comment]
Thanks @wlandau for looping me in. I think I can see how you might implement the  
`Rclean` code minimization into this. Once I get done with addressing reviewer comments, I’d be happy to put some energy into working on a `Drake` implementation in ‘code_to_function’. It looks like reducing the code used in the created function would be useful for improving project transparency and reproducibility.

**Comment by wlandau** [comment]
Sounds good, @MKLau.

I mostly like how `code_to_function()` is currently implemented. What I think `Rclean` can do is create smaller scripts to feed in as arguments.

```r
small_code <- Rclean::clean(large_script, var = "your_result")
small_script <- tempfile()
writeLines(small_code, small_script)
desired_function <- code_to_function(small_script)
```

Hmm... if the return value of the small script is always an R object, we could return the R object from the function instead of the current timestamp + `tempfile()` combo. We could think about allowing this as an option in `code_to_function()`.

**Comment by MKLau** [comment]
Yeah, with my limited perspective of Drake’s general use cases, I could see implementing both ways you just described but I’d lean toward the internal/option approach. I’ll mull it over as I get more experience with Drake and the function creation feature.

**Comment by wlandau** [comment]
> I think it would be great if the effort you outline above addresses this angle specifically for drake. I think people like to know whether $NEW_THING works with their old stuff and if it locks them into something "proprietary" (not in the commercial sense here, but in the workflow sense). I think people will want to know: Can I use drake with my existing scripts? If I have a drake workflow, does my existing script development / application workflow have to change? That sort of stuff.

@jennybc, I think some degree of friction is inevitable because `drake` is fundamentally and irrevocably function-oriented. However, we now have a workaround. With `code_to_function()`, one can retrofit `drake` to preexisting script-based projects. It is not a long-term best practice, but I think it will help people understand `drake` and try it out without a big leap of faith. @thebioengineer's [new chapter](https://ropenscilabs.github.io/drake-manual/scripts.html) walks through the details.
