### ISSUE TITLE
Document how to set template options for clustermq parallelism 

### ISSUE THREAD

**Issue by wlandau** [ropenscilabs/drake-manual#42]
Ref: https://github.com/ropensci/drake/issues/543#issue-368883883

**Comment by kendonB** [comment]
template argument to make - the latter is documented here: https://github.com/mschubert/clustermq/wiki/SLURM

My version of drake on my local computer was old and I couldn't see the template argument in the help. I can tell what to do now.

I still think it would be useful to put in the manual in the clustermq section.
