### ISSUE TITLE
Dedicated vignette on wildcard templating

### ISSUE THREAD

**Issue by wlandau** [ropenscilabs/drake-manual#5]
Ref: https://github.com/ropensci/drake/issues/388. cc @lorenzwalthert

**Comment by lorenzwalthert** [comment]
The vignette should follow the structure in https://github.com/ropensci/drake/issues/388#issuecomment-390858158.

**Comment by wlandau** [comment]
Lorenz, I just want to let you know that I am rethinking `drake`'s approach to wildcards, re: https://github.com/ropensci/drake/issues/424 and https://github.com/ropensci/drake/issues/235. I expect the [`glue`](https://github.com/tidyverse/glue) package to play a major role. I do not know how much will change, and I am open to ideas.

**Comment by wlandau** [comment]
But https://github.com/ropensci/drake/issues/235#issuecomment-398515633 already makes me less likely to change the actual user-side interface for wildcards.
