### ISSUE TITLE
Within-target parallelism section

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/drake-manual#69]
# Questions

> - In `mclapply()`, set the `mc.set.seed` argument to `FALSE`. If your computations require pseudo-random numbers (`rnorm()`, `runif()`, etc.) you will need to manually set a different seed for each parallel process, e.g.

Why? I use it in my code and haven't faced any problems yet. 

> - In `make()`, set the `lock_envir` argument to `FALSE`. This approach deactivates important reproducibility guardrails, so use with caution.

I also do not do this. What is the reason behind this?

# Suggestions

Devote an own section to "within-target parallelism". Create subsections for 

- General notes
- Execution on a single machine
- Execution on a HPC

**Comment by wlandau** [comment]
> Why? I use it in my code and haven't faced any problems yet.

From the "Random numbers" section of the help file of `parallel::mcparallel()`:

 > If ‘mc.set.seed = FALSE’, the child process has the same initial
     random number generator (RNG) state as the current R session.  If
     the RNG has been used (or ‘.Random.seed’ was restored from a saved
     workspace), the child will start drawing random numbers at the
     same point as the current session.

``` r
rnorm(1)
#> [1] 0.4506939
parallel::mclapply(c(1, 1), rnorm, mc.set.seed = FALSE, mc.cores = 2)
#> [[1]]
#> [1] -0.3738903
#> 
#> [[2]]
#> [1] -0.3738903
```

<sup>Created on 2019-03-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

> I also do not do this. What is the reason behind this?

Just if people are encountering https://github.com/ropensci/drake/issues/675 and need a quick workaround.

**Comment by pat-s** [comment]
> From the "Random numbers" section of the help file of parallel::mcparallel():

Uff, either I always interpreted that wrong or something changed recently. I remember explicitly setting this to HAVE the same RNG across all processes. 
That's ofc a bummer then. But according to the documentation I was wrong. Hmm

**Comment by wlandau** [comment]
I just added new writing based on https://github.com/ropensci/drake/issues/777#issuecomment-473412141.

**Comment by pat-s** [comment]
No worries. I would suggest to make one part of the persistent worker section extra clear:

The number of workers chosen in `prework` apply to all `future_*()` functions in the whole plan. I.e. the user needs to choose the lowest value that works for all instances in the plan.

**Comment by wlandau** [comment]
Yeah, I think something like that is worth a mention. But for the defaults, I agree with @HenrikBengtsson in https://github.com/ropensci/drake/issues/777#issuecomment-473474039. I think the first examples should rely on `future::availableCores()`. See 9cb152753903a748cb7edecef528ece074995f82.
