### ISSUE TITLE
Twitter metadata

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/drake-manual#74]
According to [the Twitter card validator](https://cards-dev.twitter.com/validator) the drake manual has less pretty cards than the dev guide, and from comparing our configurations,

* You should add a description field to the YAML of index.Rmd https://github.com/ropensci/dev_guide/blob/df87098955698b68066c4d7efe1cb5f7c93c1910/index.Rmd#L12
* I see you already have a cover-image field but the link that's generated is wrong `<meta property="og:image" content="https://ropenscilabs.github.io/drake-manualimages/logo.svg" />`. I think you could just remove the `"` see https://github.com/ropensci/dev_guide/blob/df87098955698b68066c4d7efe1cb5f7c93c1910/index.Rmd#L13

**Comment by maelle** [comment]
I'm also not sure whether the Twitter image can be SVG :thinking:

**Comment by wlandau** [comment]
Yup, you are right about the SVG issue. Time to generate a PNG.

**Comment by wlandau** [comment]
The twitter Twitter card now shows the logo. (I needed to write `/images/logo.png` rather than `images/logo.png` to get the correct link. The SVG might have worked, but resolution is not a big deal here.) Thanks for the suggestion.

**Comment by maelle** [comment]
Yay!

**Comment by maelle** [comment]
In description, maybe add a comma and a general statement about drake? "drake, an R package supporting reproducibility"?

**Comment by wlandau** [comment]
Sure: https://github.com/ropenscilabs/drake-manual/commit/76b06a61828c994fa00a4646e5d3076f20324679

**Comment by maelle** [comment]
🎉
